### ISSUE TITLE
Is there any pretrained model to use?

### ISSUE THREAD

**Issue by shuan4638** [reymond-group/OpenNMT-py#1]
I want to use the model to predict my bioreaction (substrate + enzyme) but i don't have the computational resource to train model. 
Could you upload the trained model same with the one used in paper to GitHub for public use?
Thank you.

**Comment by jonstrutz11** [comment]
@DavKre just wanted to bump this - is there any possibility to push the pretrained model to this repo for public use? This seems like a **very** powerful tool but in it's current state cannot be used or reproduced by others in the scientific community.

Or is there any way to at least get the training data used in the publication so that others can train it themselves?

**Comment by DavKre** [comment]
Hi Shuan, 
Unfortunately, the model was trained from private Reaxys data, therefore we are not allowed to share the trained model. 
Best regards,
David
